//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 7/22/2018 1:06:03 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using NHibernate.Classic;

namespace SammakEnterprise.JobSearch.Middle.Entities
{

    /// <summary>
    /// There are no comments for SammakEnterprise.JobSearch.Middle.Entities.Person, SammakEnterprise.JobSearch.Middle in the schema.
    /// </summary>
    public abstract partial class Person : DomainBase, IValidatable {
    
        #region Extensibility Method Definitions
        
        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        public override bool Equals(object obj)
        {
          if (!base.Equals(obj))
          {
            return false;
          }

          Person toCompare = obj as Person;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.FirstName, toCompare.FirstName))
            return false;
          if (!Object.Equals(this.LastName, toCompare.LastName))
            return false;
          
          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          return hashCode;
        }
        
        #endregion
        /// <summary>
        /// There are no comments for Person constructor in the schema.
        /// </summary>
        public Person()
        {
            this.Emails = new List<Email>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for FirstName in the schema.
        /// </summary>
        public virtual string FirstName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for LastName in the schema.
        /// </summary>
        public virtual string LastName
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Emails in the schema.
        /// </summary>
        public virtual IList<Email> Emails
        {
            get;
            set;
        }
    }

}
