//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 7/22/2018 1:06:03 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.ComponentModel;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using NHibernate.Classic;

namespace SammakEnterprise.JobSearch.Middle.Entities
{

    /// <summary>
    /// There are no comments for SammakEnterprise.JobSearch.Middle.Entities.EmployeeRole, SammakEnterprise.JobSearch.Middle in the schema.
    /// </summary>
    public enum EmployeeRole : short
 {
    
        /// <summary>
        /// There are no comments for EmployeeRole.ItManager in the schema.
        /// </summary>
        ItManager,    
        /// <summary>
        /// There are no comments for EmployeeRole.HiringManager in the schema.
        /// </summary>
        HiringManager,    
        /// <summary>
        /// There are no comments for EmployeeRole.PrincipalDeveloper in the schema.
        /// </summary>
        PrincipalDeveloper,    
        /// <summary>
        /// There are no comments for EmployeeRole.SeniorDeveloper in the schema.
        /// </summary>
        SeniorDeveloper,    
        /// <summary>
        /// There are no comments for EmployeeRole.Developer in the schema.
        /// </summary>
        Developer,    
        /// <summary>
        /// There are no comments for EmployeeRole.ScrumMaster in the schema.
        /// </summary>
        ScrumMaster,    
        /// <summary>
        /// There are no comments for EmployeeRole.Recruiter in the schema.
        /// </summary>
        Recruiter,    
        /// <summary>
        /// There are no comments for EmployeeRole.ProgramManager in the schema.
        /// </summary>
        ProgramManager
    }

    /// <summary>
    /// This type helps NHibernate map an enum string instead of the int.
    /// </summary>      
    public class EmployeeRoleEnumStringType : NHibernate.Type.EnumStringType
    {
        public EmployeeRoleEnumStringType() : base(typeof(EmployeeRole))
        {
        }
    }

}
